Repository SOPT-all/36-COLLABORATION-SERVER-KYOBOBOOK, pull requests merged in 2025-05, with the labels that each got.

#3 [FEAT] 공통응답코드 추가
  build.gradle
  src/main/java/org/sopt/global/advice/GlobalExceptionHandler.java
  src/main/java/org/sopt/global/dto/ErrorDTO.java
  src/main/java/org/sopt/global/dto/ResponseDTO.java
  src/main/java/org/sopt/global/exception/BusinessException.java
  src/main/java/org/sopt/global/message/business/BusinessErrorMessage.java
  src/main/java/org/sopt/global/message/business/CommonErrorMessage.java
  src/main/java/org/sopt/global/message/business/DefaultErrorMessage.java
Labels: 🐰수민🐰

#7 [FEAT] book domain 기본코드설정
  src/main/java/org/sopt/controller/book/BookController.java
  src/main/java/org/sopt/domain/book/Book.java
  src/main/java/org/sopt/domain/review/Empathy.java
  src/main/java/org/sopt/domain/review/Review.java
  src/main/java/org/sopt/repository/book/BookRepository.java
  src/main/java/org/sopt/service/book/BookService.java
Labels: 🦊지수🦊, ✨ Feature

#10 [DEPLOY] CI/CD
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/main/java/org/sopt/Main.java
  src/main/java/org/sopt/global/message/business/BookErrorMesseage.java
Labels: 🐰수민🐰, 🌏 Deploy

#15 [FEAT] 도서상세정보조회API구현
  src/main/java/org/sopt/controller/book/BookController.java
  src/main/java/org/sopt/dto/book/response/BookResponseDTO.java
  src/main/java/org/sopt/dto/book/response/BookResponseDetailDTO.java
  src/main/java/org/sopt/global/dto/ErrorDTO.java
  src/main/java/org/sopt/global/message/business/BookErrorMessage.java
  src/main/java/org/sopt/service/book/BookService.java
Labels: 🦊지수🦊, ✨ Feature
